# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DigitalSketchMappingTool
                                 A QGIS plugin
 Digital sketch mapping tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-20
        copyright            : (C) 2025 by ESK Spatial
        email                : sakna.hewagalamulage@eskspatial.com.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DigitalSketchMappingTool class from file DigitalSketchMappingTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    import sys
    import os

    # Ensure the plugin's directory is in the system path
    plugin_dir = os.path.dirname(__file__)
    if plugin_dir not in sys.path:
        sys.path.append(plugin_dir)

    from .digital_sketch_mapping_tool import DigitalSketchMappingTool
    return DigitalSketchMappingTool(iface)
