# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DigitalSketchMappingTool
                                 A QGIS plugin
 Digital sketch mapping tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by ESK Spatial
        email                : sakna.hewagalamulage@eskspatial.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from collections import deque

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QPushButton, QVBoxLayout, QFileDialog, QDialog, QWidget, QHBoxLayout, QSpacerItem, QSizePolicy
from qgis.core import QgsApplication, QgsFields, QgsCoordinateReferenceSystem, QgsVectorFileWriter, QgsWkbTypes, QgsVectorLayer, QgsProject, QgsRasterLayer, QgsPointXY, QgsCoordinateTransform, QgsRectangle, QgsField
from datetime import datetime
from helper import create_geopackage_file, split_array_to_chunks, adjust_color, get_current_date, get_current_time
from qgis.core import QgsSettings, QgsExpression, QgsSymbol, QgsRendererCategory, QgsCategorizedSymbolRenderer, QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, Qgis
from PyQt5.QtWidgets import QWidgetAction, QToolButton

from stream_digitizing_tool import StreamDigitizingTool
from multi_line_tool import MultiLineDigitizingTool
from feature_identify_tool import FeatureIdentifyTool
from .app_settings import AppSettingsDialog
from keypad_manager import KeypadManager

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .digital_sketch_mapping_tool_dockwidget import DigitalSketchMappingToolDockWidget
import os.path
try:
    from osgeo import ogr
except ImportError:
    import ogr

_plugin_name_ = "app_tester"
_plugin_directory_ = os.path.dirname(__file__)

def apply_symbology(layer, iface):
    categories = []

    unique_colors = {f["colour"] for f in layer.getFeatures() if f["colour"]}

    for hex_color in unique_colors:
        if not hex_color.startswith("#"):  # Ensure valid hex format
            continue

        symbol = QgsSymbol.defaultSymbol(layer.geometryType())
        symbol.setColor(QColor(hex_color))  # Convert hex to QColor
        category = QgsRendererCategory(hex_color, symbol, hex_color)
        categories.append(category)

    renderer = QgsCategorizedSymbolRenderer("colour", categories)
    layer.setRenderer(renderer)

    label_settings = QgsPalLayerSettings()
    label_settings.fieldName = "Code"
    label_settings.enabled = True
    layer.setLabeling(QgsVectorLayerSimpleLabeling(label_settings))

    layer.triggerRepaint()
    iface.mapCanvas().refresh()


def delete_feature(layer, fid):
    layer.startEditing()
    layer.deleteFeature(fid)
    layer.commitChanges()


class DigitalSketchMappingTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.created_layers_stack = deque()
        self.digitizing_tool = None
        self.iface = iface
        self.canvas = self.iface.mapCanvas()
        self.folder_location = None
        self.feature_string = ""
        self.selected_colour = "#3dc6177f"
        self.point_layer = None
        self.line_layer = None
        self.polygon_layer = None
        self.plugin_name = _plugin_name_
        self.keypad_manager = KeypadManager()
        self.pressed_btn = None
        self.attributes = None

        self.bing_maps_url = (
            "https://t0.tiles.virtualearth.net/tiles/a{q}.jpeg?g=685&mkt=en-us&n=z"
        )
        self.bing_layer_name = "Bing Satellite Imagery"

        # Location coordinates (longitude, latitude)
        self.location_lon = 151.2093
        self.location_lat = -33.8688

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DigitalSketchMappingTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Digital Sketch Mapping Tool')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'DigitalSketchMappingTool')
        self.toolbar.setObjectName(u'DigitalSketchMappingTool')

        #print "** INITIALIZING DigitalSketchMappingTool"

        self.pluginIsActive = False
        self.digital_sketch_widget = DigitalSketchMappingToolDockWidget()


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DigitalSketchMappingTool', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        settings = QSettings()

        attr_value = str(settings.value("qgis/digitizing/disable_enter_attribute_values_dialog", "false")).lower()
        QgsApplication.messageLog().logMessage(f'attr_value: {attr_value}.', "DigitalSketchPlugin")
        QgsApplication.messageLog().logMessage(f'settings: {settings.fileName()}.', "DigitalSketchPlugin")
        if attr_value == 'false':
            QgsApplication.messageLog().logMessage("updating to true", 'DigitalSketchPlugin')

        icon_path = ':/plugins/digital_sketch_mapping_tool/icons/icon.png'

        QgsApplication.messageLog().logMessage(f"icon_path {icon_path}", 'DigitalSketchPlugin')

        self.add_action(
            icon_path,
            text=self.tr(u'Digital sketch mapping tool'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.check_and_get_folder()
        self.digital_sketch_widget.setFolderPushButton.clicked.connect(self.__set_folder_location)
        self.digital_sketch_widget.mColorButton.colorChanged.connect(self.__colour_changed)
        self.digital_sketch_widget.savePushButton.clicked.connect(self.save_layers)
        self.digital_sketch_widget.settingPushButton.clicked.connect(self.open_settings)
        self.digital_sketch_widget.donePushButton.clicked.connect(self.done_digitizing)
        self.digital_sketch_widget.deletePushButton.clicked.connect(self.delete_last_feature)

        self.digital_sketch_widget.linePushButton.clicked.connect(
            lambda: self.setup_digitizing(self.line_layer, 'line'))
        self.digital_sketch_widget.pointPushButton.clicked.connect(
            lambda: self.setup_digitizing(self.point_layer, 'point'))
        self.digital_sketch_widget.polygonPushButton.clicked.connect(
            lambda: self.setup_digitizing(self.polygon_layer, 'polygon'))

    # --------------------------------------------------------------------------

    def __load_bing_maps(self):
        # Load Bing Maps XYZ layer
        xyz_uri = f"type=xyz&url={self.bing_maps_url}&zmax=18&zmin=0&http-header:referer="
        bing_layer = QgsRasterLayer(xyz_uri, self.bing_layer_name, "wms")

        if not bing_layer.isValid():
            QgsApplication.messageLog().logMessage("Failed to load Bing Maps layer.", "DigitalSketchPlugin")
            return

        QgsProject.instance().addMapLayer(bing_layer)
        self.iface.setActiveLayer(bing_layer)

    # --------------------------------------------------------------------------

    def __zoom_to_location(self):
        self.canvas.setDestinationCrs(QgsCoordinateReferenceSystem('EPSG:3857'))

        # Convert location coordinates to Web Mercator
        location_point = QgsPointXY(self.location_lon, self.location_lat)
        crs_src = QgsCoordinateReferenceSystem('EPSG:4326')
        crs_dest = QgsCoordinateReferenceSystem('EPSG:3857')
        xform = QgsCoordinateTransform(crs_src, crs_dest, QgsProject.instance())
        location_transformed = xform.transform(location_point)

        # Create an extent centered on location
        zoom_width = 20000  # meters
        extent = QgsRectangle(
            location_transformed.x() - zoom_width,
            location_transformed.y() - zoom_width,
            location_transformed.x() + zoom_width,
            location_transformed.y() + zoom_width
        )

        # Set the extent and refresh
        self.canvas.setExtent(extent)
        self.canvas.refresh()

    # --------------------------------------------------------------------------

    def __set_folder_location(self):
        folder = self.digital_sketch_widget.folderQgsFileWidget.filePath()
        QgsApplication.messageLog().logMessage(f'Directory path {folder}.', 'DigitalSketchPlugin')
        if folder:
            self.folder_location = folder
            self.__load_bing_maps()
            self.__create_geopackage_file()
            self.__zoom_to_location()

    # --------------------------------------------------------------------------

    def __populate_categories(self):
        categories = self.keypad_manager.get_selected_categories()
        attr_box = self.digital_sketch_widget.categoryAttrVerticalLayout
        if not attr_box.isEmpty():
            QgsApplication.messageLog().logMessage('Need to remove', 'DigitalSketchPlugin')
            while attr_box.count():
                QgsApplication.messageLog().logMessage("looping and deleting", 'DigitalSketchPlugin')
                item = attr_box.takeAt(0)
                attr_box.removeWidget(item.widget())

        for cat in categories:
            QgsApplication.messageLog().logMessage(f'colour: {cat.colour}', 'DigitalSketchPlugin')
            if len(cat.items) > 3:
                QgsApplication.messageLog().logMessage("items greater than 3", 'DigitalSketchPlugin')
                chunks = split_array_to_chunks(cat.items)
                for chunk in chunks:
                    attr_box.addWidget(self.__populate_buttons_from_list(chunk, cat.colour))

            else:
                attr_box.addWidget(self.__populate_buttons_from_list(cat.items, cat.colour))

    # --------------------------------------------------------------------------

    def __colour_changed(self, colour):
        self.selected_colour = colour.name()
        QgsApplication.messageLog().logMessage(f'selected colour: {self.selected_colour}', 'DigitalSketchPlugin')

    # --------------------------------------------------------------------------

    def __hiding_folder_control(self):
        self.digital_sketch_widget.folderLbl.setVisible(False)
        self.digital_sketch_widget.folderQgsFileWidget.setVisible(False)
        self.digital_sketch_widget.setFolderPushButton.setVisible(False)

    # --------------------------------------------------------------------------

    def __button_clicked(self, button_name):
        if self.feature_string == "":
            self.feature_string = button_name

        elif button_name not in self.feature_string:
            self.feature_string = f'{self.feature_string}_{button_name}'

        self.__update_code_line_edit()

        QgsApplication.messageLog().logMessage(
            f'clicked button {button_name} feature_string {self.feature_string}.', 'DigitalSketchPlugin')

    # --------------------------------------------------------------------------

    def setup_digitizing(self, layer, layer_type):
        """Setup digitizing mode with automated attribute handling"""
        # Make layer active and editable
        self.__check_for_current_selection(layer_type)
        self.iface.setActiveLayer(layer)
        layer.startEditing()

        if layer_type == 'line':
            QgsApplication.messageLog().logMessage("line layer", 'DigitalSketchPlugin')
            self.enable_feature_create("Add Line Feature")
            self.setup_stream_digitizing(layer, 'line', True)

        elif layer_type == 'point':
            # TODO
            QgsApplication.messageLog().logMessage("point layer", 'DigitalSketchPlugin')
            self.enable_feature_create("Add Point Feature")

        elif layer_type == 'polygon':
            QgsApplication.messageLog().logMessage("polygon layer", 'DigitalSketchPlugin')
            self.enable_feature_create("Add Polygon Feature")
            self.setup_stream_digitizing(layer, layer_type)

        # Connect to feature added signal
        layer.featureAdded.connect(lambda fid: self.populate_attributes(fid, layer, layer_type))

    # --------------------------------------------------------------------------

    def save_layers(self):
        QgsApplication.messageLog().logMessage("Save layers is called", 'DigitalSketchPlugin')
        if self.point_layer.isEditable():
            QgsApplication.messageLog().logMessage("Point layer is editable", 'DigitalSketchPlugin')
            self.point_layer.commitChanges()  # Save the changes
            self.point_layer.stopEditing(True)  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to point layer!",
                                                level=Qgis.Success)

        if self.line_layer.isEditable():
            QgsApplication.messageLog().logMessage("Line layer is editable", 'DigitalSketchPlugin')
            self.line_layer.commitChanges()  # Save the changes
            self.line_layer.stopEditing(True)  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to line layer!",
                                                level=Qgis.Success)

        if self.polygon_layer.isEditable():
            QgsApplication.messageLog().logMessage("Polygon layer is editable", 'DigitalSketchPlugin')
            self.polygon_layer.commitChanges()  # Save the changes
            self.polygon_layer.stopEditing(True)  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to polygon layer!",
                                                level=Qgis.Success)

        self.remove_map_tool()
        self.__check_for_current_selection()

    # --------------------------------------------------------------------------

    def open_settings(self):
        QgsApplication.messageLog().logMessage("Open settings is called", 'DigitalSketchPlugin')

        settings_dialog = AppSettingsDialog(self.keypad_manager, self.attributes)
        if settings_dialog.exec_() == QDialog.Accepted:
            self.attributes = settings_dialog.get_attributes()
            self.__populate_categories()

    # --------------------------------------------------------------------------

    def done_digitizing(self):
        QgsApplication.messageLog().logMessage("Done Digitizing is called", 'DigitalSketchPlugin')
        self.digitizing_tool.save_feature()

    # --------------------------------------------------------------------------

    def delete_last_feature(self):
        if len(self.created_layers_stack) == 0:
            return

        last_layer = self.created_layers_stack.pop()

        if last_layer["type"] == "line":
            delete_feature(self.line_layer, last_layer["fid"])

        elif last_layer["type"] == "point":
            delete_feature(self.point_layer, last_layer["fid"])

        elif last_layer["type"] == "polygon":
            delete_feature(self.polygon_layer, last_layer["fid"])

    # --------------------------------------------------------------------------

    def enable_feature_create(self, action_name):
        toolbar = self.iface.digitizeToolBar()
        QgsApplication.messageLog().logMessage(f"Toolbar found: {toolbar.objectName()}", 'DigitalSketchPlugin')

        # for action in toolbar.actions():
        #     action_text = action.text() if action.text() else "[No Text]"
        #     if action_text == action_name:
        #         action.trigger()

    # --------------------------------------------------------------------------

    def setup_stream_digitizing(self, layer, layer_type, is_multipart=False):
        """Setup digitizing mode using stylus events"""
        self.iface.setActiveLayer(layer)
        layer.startEditing()

        if is_multipart:
            QgsApplication.messageLog().logMessage("multipart", 'DigitalSketchPlugin')
            self.digitizing_tool = MultiLineDigitizingTool(self.iface, layer)
        else:
            QgsApplication.messageLog().logMessage("single ", 'DigitalSketchPlugin')
            self.digitizing_tool = StreamDigitizingTool(self.iface, layer, layer_type)

        self.iface.mapCanvas().setMapTool(self.digitizing_tool)

    # --------------------------------------------------------------------------

    def remove_map_tool(self):
        self.iface.mapCanvas().unsetMapTool(self.digitizing_tool)
        self.iface.actionPan().trigger()

    # --------------------------------------------------------------------------

    def enable_stream_digitize(self):
        toolbar = self.iface.digitizeToolBar()
        QgsApplication.messageLog().logMessage(f"Toolbar found: {toolbar.objectName()}", 'DigitalSketchPlugin')

        action_triggered = False
        for action in toolbar.actions():
            if action_triggered:
                break
            else:
                if isinstance(action, QWidgetAction):  # If it's a QWidgetAction, get its widget
                    widget = action.defaultWidget()
                    if widget:
                        action_text = widget.text() if hasattr(widget, "text") else "[No Text]"
                        QgsApplication.messageLog().logMessage(
                            f"QWidgetAction - Text: {action_text} is menu {isinstance(widget, QToolButton)}",
                            'DigitalSketchPlugin')

                        if "Digitiz" in action_text:
                            sub_items = widget.menu()
                            if sub_items:
                                sub_actions = sub_items.actions()
                                for inner_action in sub_actions:
                                    # Look for the "Stream Digitizing" action in the toolbar
                                    QgsApplication.messageLog().logMessage(f"Action - Text: {inner_action.text()}",
                                                                           'DigitalSketchPlugin')
                                    if inner_action.text() == "Stream Digitizing" and not inner_action.isChecked():
                                        inner_action.trigger()
                                        inner_action.toggle()
                                        action_triggered = True
                                        break

                                    elif inner_action.text() == "Stream Digitizing" and inner_action.isChecked():
                                        action_triggered = True
                                        break

                                    elif inner_action.isChecked():
                                        QgsApplication.messageLog().logMessage(
                                            f"Action - is checked: {inner_action.text()}",
                                            'DigitalSketchPlugin')

    # --------------------------------------------------------------------------

    def populate_attributes(self, fid, layer, layer_type):
        """Automatically populate attributes for new features"""
        feature = layer.getFeature(fid)
        self.created_layers_stack.append({"type": layer_type, "fid": fid})

        if layer_type == 'note':
            feature.setAttribute('colour', "#FF0000")
            feature.setAttribute('Code', "")

        else:
            feature.setAttribute('colour', self.selected_colour)
            feature.setAttribute('shape', layer_type)
            feature.setAttribute('Code', f"{self.feature_string}")
            feature.setAttribute('Date', get_current_date())
            feature.setAttribute('Time', get_current_time())

        # Update the feature
        layer.updateFeature(feature)
        apply_symbology(layer, self.iface)

        if layer.isEditable():
            QgsApplication.messageLog().logMessage('layer is editable', 'DigitalSketchPlugin')
            # layer.commitChanges()
            # layer.startEditing()

        self.feature_string = ""
        self.__update_code_line_edit()
        QgsApplication.messageLog().logMessage('finished updating symbology', 'DigitalSketchPlugin')

    # --------------------------------------------------------------------------

    def __create_geopackage_file(self):
        QgsApplication.messageLog().logMessage('creating new gpkg file', 'DigitalSketchPlugin')
        date_time_str = datetime.now().strftime("%d-%m-%Y_%I-%M-%p")
        gpkg_file_name = f"{date_time_str}.gpkg"
        gpkg_file_name = os.path.join(self.folder_location, gpkg_file_name)
        QgsApplication.messageLog().logMessage(f'file name: {gpkg_file_name} file path: {gpkg_file_name}',
                                               'DigitalSketchPlugin')

        # get project CRS information
        crs_ors = str(self.canvas.mapSettings().destinationCrs().toProj())
        create_geopackage_file(gpkg_file_name, crs_ors)

        self.point_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=points", "points", "ogr")
        self.line_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=lines", "lines", "ogr")
        self.polygon_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=polygons", "polygons", "ogr")

        self.point_layer.loadNamedStyle(os.path.join(os.path.dirname(__file__), "plugin_style.qml"))
        self.polygon_layer.loadNamedStyle(os.path.join(os.path.dirname(__file__), "plugin_style.qml"))
        self.line_layer.loadNamedStyle(os.path.join(os.path.dirname(__file__), "plugin_style.qml"))

        QgsProject.instance().addMapLayer(self.point_layer)
        QgsProject.instance().addMapLayer(self.line_layer)
        QgsProject.instance().addMapLayer(self.polygon_layer)

        # TODO
        # point_tool = FeatureIdentifyTool(self.iface, self.point_layer)
        # self.iface.mapCanvas().setMapTool(point_tool)

        # polygon_tool = FeatureIdentifyTool(self.iface)
        # self.iface.mapCanvas().setMapTool(polygon_tool)

        # line_tool = FeatureIdentifyTool(self.iface, self.line_layer)
        # self.iface.mapCanvas().setMapTool(line_tool)

        self.canvas.refresh()

    # --------------------------------------------------------------------------

    def check_and_get_folder(self):
        if not self.folder_location:  # Check if empty or None
            QgsApplication.messageLog().logMessage('folder not set', 'DigitalSketchPlugin')
            self.digital_sketch_widget.folderLbl.setVisible(True)
            self.digital_sketch_widget.folderQgsFileWidget.setVisible(True)
            self.digital_sketch_widget.setFolderPushButton.setVisible(True)

    #--------------------------------------------------------------------------

    def  __check_for_current_selection(self, selection=None):
        if self.pressed_btn is not None:
            QgsApplication.messageLog().logMessage(f"btn already pressed {self.pressed_btn}", 'DigitalSketchPlugin')
            # self.save_layers()

            if self.pressed_btn == 'line':
                self.digital_sketch_widget.linePushButton.setChecked(False)
            elif self.pressed_btn == 'point':
                self.digital_sketch_widget.pointPushButton.setChecked(False)
            elif self.pressed_btn == 'polygon':
                self.digital_sketch_widget.polygonPushButton.setChecked(False)
            # elif self.pressed_btn == 'notes':
            #     self.digital_sketch_widget.notesPushButton.setChecked(False)

        if selection is not  None:
            self.pressed_btn = selection

    # --------------------------------------------------------------------------

    def __populate_buttons_from_list(self, items, colour):
        layout = QHBoxLayout()
        widget = QWidget()
        item_count = len(items)
        light_colour = adjust_color(colour, 30)
        # dark_colour = adjust_color(colour, -15)
        for item in items:
            btn = QPushButton(item)
            btn.setMinimumHeight(self.attributes["height"])
            btn.setMaximumHeight(self.attributes["height"])
            btn.setMinimumWidth(self.attributes["width"])
            btn.setMaximumWidth(self.attributes["width"])
            btn.setFont(self.attributes["font"])
            btn.setStyleSheet(f"""
                            QPushButton {{
                                background-color: {colour};
                                color: {self.attributes["colour"]};
                                border-radius: 5px;
                                padding: 5px 5x;
                            }}
                            QPushButton:hover {{
                                background-color: {light_colour};
                            }}
                            """)
            layout.addWidget(btn)
            btn.clicked.connect(lambda checked, btn_name=item: self.__button_clicked(btn_name))
            layout.setContentsMargins(2, 2, 2, 2)
            layout.setSpacing(5)

        # if item_count < 3:
        #     QgsApplication.messageLog().logMessage("Setting item_cefefeount space l121alala", 'DigitalSketchPlugin')
        #     # layout.addItem(QSpacerItem(40, 30, QSizePolicy.Expanding, QSizePolicy.Minimum))
        #     layout.insertStretch(-1,100)

        # layout.insertStretch(0, 1)  # Stretch before first button
        # layout.addStretch(1)  # Stretch after last button
        layout.addItem(QSpacerItem(40, 30, QSizePolicy.Expanding, QSizePolicy.Minimum))
        layout.insertStretch(-1, 100)
        widget.setLayout(layout)
        return widget

    # --------------------------------------------------------------------------

    def __update_code_line_edit(self):
        self.digital_sketch_widget.lineEdit.setText(self.feature_string)

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING DigitalSketchMappingTool"

        # disconnects
        self.digital_sketch_widget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD DigitalSketchMappingTool"

        # for action in self.actions:
        #     self.iface.removePluginMenu(
        #         self.tr(u'&Digital Sketch Mapping Tool'),
        #         action)
        #     self.iface.removeToolBarIcon(action)
        # # remove the toolbar
        # del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING DigitalSketchMappingTool"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)

            # connect to provide cleanup on closing of dockwidget
            self.digital_sketch_widget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.digital_sketch_widget)
            self.digital_sketch_widget.show()
