# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DigitalSketchMappingTool
                                 A QGIS plugin
 Digital sketch mapping tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by ESK Spatial
        email                : sakna.hewagalamulage@eskspatial.com.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import traceback
from collections import deque

from PyQt5.QtWidgets import QRadioButton, QStackedWidget
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QVariant, QMargins
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import (QAction, QFileDialog, QMessageBox, QPushButton, QVBoxLayout, QFileDialog, QDialog,
                                 QWidget, QHBoxLayout, QSpacerItem, QSizePolicy, QGroupBox, QScrollArea, QToolButton,
                                 QWidgetAction)
from qgis.core import (QgsApplication, QgsFields, QgsCoordinateReferenceSystem, QgsVectorFileWriter, QgsWkbTypes,
                       QgsVectorLayer, QgsProject, QgsRasterLayer, QgsPointXY, QgsCoordinateTransform, QgsRectangle,
                       QgsField, QgsGpsConnection)
from datetime import datetime

from custom_zoom_tool import CustomZoomTool
from helper import create_geopackage_file, split_array_to_chunks, adjust_color, show_delete_confirmation, \
    get_existing_layers, get_bing_layer
from qgis.core import (QgsSettings, QgsExpression, QgsSymbol, QgsRendererCategory, QgsCategorizedSymbolRenderer,
                       QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, Qgis)
from data.db_init import DbInit
from stream_digitizing_tool import StreamDigitizingTool
from multi_line_tool import MultiLineDigitizingTool
from feature_identify_tool import FeatureIdentifyTool
from .app_settings import AppSettingsDialog
from keypad_manager import KeypadManager

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .digital_sketch_mapping_tool_dockwidget import DigitalSketchMappingToolDockWidget
import os.path

try:
    from osgeo import ogr
except ImportError:
    import ogr

_plugin_name_ = "digital_sketch_mapping_tool"
_plugin_directory_ = os.path.dirname(__file__)

def apply_symbology(layer, iface):
    categories = []

    unique_colors = {f["colour"] for f in layer.getFeatures() if f["colour"]}

    for hex_color in unique_colors:
        if not hex_color.startswith("#"):  # Ensure valid hex format
            continue

        symbol = QgsSymbol.defaultSymbol(layer.geometryType())
        symbol.setColor(QColor(hex_color))  # Convert hex to QColor
        category = QgsRendererCategory(hex_color, symbol, hex_color)
        categories.append(category)

    renderer = QgsCategorizedSymbolRenderer("colour", categories)
    layer.setRenderer(renderer)
    layer.triggerRepaint()
    iface.mapCanvas().refresh()


def delete_keypad_items(attr_box)    :
    if not attr_box.isEmpty():
        QgsApplication.messageLog().logMessage('Need to remove', 'DigitalSketchPlugin')
        count = attr_box.count()
        if count > 0 and attr_box.itemAt(count - 1).spacerItem() is not None:
            attr_box.takeAt(count - 1)  # Remove the existing spacer
        while attr_box.count():
            item = attr_box.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()


class DigitalSketchMappingTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Save reference to the QGIS interface
        self.created_layers_stack = deque()
        self.digitizing_tool = None
        self.iface = iface
        self.canvas = self.iface.mapCanvas()
        self.folder_location = None
        self.feature_string = ""
        self.selected_colour = "#3dc61780"
        self.folder_location_set = False
        self.use_existing = False
        self.point_layer = None
        self.line_layer = None
        self.polygon_layer = None
        self.plugin_name = _plugin_name_
        self.keypad_manager = KeypadManager()
        self.pressed_btn = None
        self.attributes = None
        self.layers_saved = 0
        self.selected_attribute = None
        self.highlight = None
        self.vertex_marker = None
        self.zoom_factor = 2
        self.zoom_tool = CustomZoomTool(self.iface, self.zoom_factor)
        self.multiline_tool = None
        self.polygon_tool = None
        self.point_tool = None
        self.point_style = os.path.join(self.plugin_dir, "styles", "geolink_points_240325.qml")
        self.polygon_style = os.path.join(self.plugin_dir, "styles", "geolink_polygons_240325.qml")
        self.line_style = os.path.join(self.plugin_dir, "styles", "geolink_lines_240325.qml")
        self.clicked_buttons = set()
        self.text_changed = False
        self.project_crs = None
        self.feature_identify_tool = FeatureIdentifyTool(self.iface, self)
        self.bing_maps_url = (
            "https://t0.tiles.virtualearth.net/tiles/a{q}.jpeg?g=685&mkt=en-us&n=z"
        )
        self.bing_layer_name = "Bing Satellite Imagery"
        self.db_path = os.path.join(self.plugin_dir, "data", "keypad_data.sqlite")
        self.db_initializer = DbInit(self.db_path)
        self.new_project_removing_existing = False

        # Location coordinates (longitude, latitude)
        self.location_lon = 151.2093
        self.location_lat = -33.8688
        self.iface.newProjectCreated.connect(self.on_project_create_or_read)
        self.iface.projectRead.connect(self.on_project_create_or_read)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DigitalSketchMappingTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Digital Sketch Mapping Tool')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'DigitalSketchMappingTool')
        self.toolbar.setObjectName(u'DigitalSketchMappingTool')

        #print "** INITIALIZING DigitalSketchMappingTool"

        self.pluginIsActive = False
        self.digital_sketch_widget = DigitalSketchMappingToolDockWidget()


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DigitalSketchMappingTool', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        settings = QSettings()
        self.init_database_if_not_exists()
        attr_value = str(settings.value("qgis/digitizing/disable_enter_attribute_values_dialog", "false")).lower()
        QgsApplication.messageLog().logMessage(f'attr_value: {attr_value}.', "DigitalSketchPlugin")
        QgsApplication.messageLog().logMessage(f'settings: {settings.fileName()}.', "DigitalSketchPlugin")
        if attr_value == 'false':
            QgsApplication.messageLog().logMessage("updating to true", 'DigitalSketchPlugin')

        icon_path = ':/plugins/digital_sketch_mapping_tool/icons/icon.png'

        QgsApplication.messageLog().logMessage(f"icon_path {icon_path}", 'DigitalSketchPlugin')

        self.add_action(
            icon_path,
            text=self.tr(u'Digital sketch mapping tool'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.digital_sketch_widget.zoomInPushButton.clicked.connect(lambda: self.zoom_to_map(True))
        self.digital_sketch_widget.zoomOutPushButton.clicked.connect(lambda: self.zoom_to_map(False))

        self.digital_sketch_widget.saveAndPanPushButton.clicked.connect(self.save_and_pan)
        self.digital_sketch_widget.selectPushButton.clicked.connect(self.setup_feature_identify_tool)
        self.digital_sketch_widget.settingPushButton.clicked.connect(self.open_settings)
        self.digital_sketch_widget.donePushButton.clicked.connect(self.done_digitizing)
        self.digital_sketch_widget.deletePushButton.clicked.connect(self.remove_feature)

        self.digital_sketch_widget.codeLineEdit.textEdited.connect(self.code_text_changed)
        self.digital_sketch_widget.codeLineEdit.editingFinished.connect(self.code_text_changed_finished)

        self.digital_sketch_widget.linePushButton.clicked.connect(
            lambda: self.setup_digitizing(self.line_layer, 'lines'))
        self.digital_sketch_widget.pointPushButton.clicked.connect(
            lambda: self.setup_digitizing(self.point_layer, 'points'))
        self.digital_sketch_widget.polygonPushButton.clicked.connect(
            lambda: self.setup_digitizing(self.polygon_layer, 'polygons'))

        QgsProject.instance().layerRemoved.connect(self.layer_removed)

    # --------------------------------------------------------------------------

    def init_database_if_not_exists(self):
        if not os.path.exists(self.db_path):
            db_init_path = os.path.join(self.plugin_dir, 'data', 'db_init.py')
            if os.path.exists(db_init_path):
                self.db_initializer.init_db()

            else:
                raise FileNotFoundError("data/db_init.py not found to initialize the database.")
    # --------------------------------------------------------------------------

    def on_project_create_or_read(self):
        QgsApplication.messageLog().logMessage('project create/read', 'DigitalSketchPlugin')
        self.folder_location_set = False
        self.use_existing = False
        if self.attributes is not None:
            self.attributes["project_changed"] = True

    # --------------------------------------------------------------------------

    def remove_layers(self):
        try:
            QgsProject.instance().layerRemoved.disconnect(self.layer_removed)
        except Exception as e:
            QgsApplication.messageLog().logMessage(f"error byuub: {e}", "DigitalSketchPlugin")

        try:
            bing_layer = get_bing_layer(self.bing_layer_name)
            if bool(bing_layer):
                QgsProject.instance().removeMapLayer(bing_layer.get("l_id"))
            layers = get_existing_layers()
            if len(layers) > 0:
                for l_id in layers:
                    QgsProject.instance().removeMapLayer(l_id)

        finally:
            QgsProject.instance().layerRemoved.connect(self.layer_removed)


    # --------------------------------------------------------------------------

    def set_folder_location(self):
        folder = self.attributes['folder_path']
        QgsApplication.messageLog().logMessage(f"Directory path {folder}. add_bing: {self.attributes['add_bing_imagery']}", "DigitalSketchPlugin")
        if folder:
            self.folder_location = folder
            if self.attributes['add_bing_imagery']:
                self.load_bing_maps()
            self.create_geopackage_file(self.attributes['project_name'])
            self.zoom_to_location()

    # --------------------------------------------------------------------------

    def set_layer_from_existing(self, layers):
        self.use_existing =True
        self.point_layer = layers['points'] if "points" in layers else None
        self.polygon_layer = layers['polygons'] if "polygons" in layers else None
        self.line_layer = layers['lines'] if "lines" in layers else None

        self.set_style_and_digitizing_tool()

    # --------------------------------------------------------------------------

    def load_bing_maps(self):
        # Load Bing Maps XYZ layer
        xyz_uri = f"type=xyz&url={self.bing_maps_url}&zmax=18&zmin=0&http-header:referer="
        bing_layer = QgsRasterLayer(xyz_uri, self.bing_layer_name, "wms")

        if not bing_layer.isValid():
            QgsApplication.messageLog().logMessage("Failed to load Bing Maps layer.", "DigitalSketchPlugin")
            return

        QgsProject.instance().addMapLayer(bing_layer, False)
        QgsProject.instance().layerTreeRoot().addLayer(bing_layer)

    # --------------------------------------------------------------------------

    def zoom_to_location(self):
        self.canvas.setDestinationCrs(QgsCoordinateReferenceSystem('EPSG:3857'))

        # Convert location coordinates to Web Mercator
        location_point = QgsPointXY(self.location_lon, self.location_lat)
        crs_src = QgsCoordinateReferenceSystem('EPSG:4326')
        crs_dest = QgsCoordinateReferenceSystem('EPSG:3857')
        xform = QgsCoordinateTransform(crs_src, crs_dest, QgsProject.instance())
        location_transformed = xform.transform(location_point)

        # Create an extent centered on location
        zoom_width = 20000  # meters
        extent = QgsRectangle(
            location_transformed.x() - zoom_width,
            location_transformed.y() - zoom_width,
            location_transformed.x() + zoom_width,
            location_transformed.y() + zoom_width
        )

        # Set the extent and refresh
        self.canvas.setExtent(extent)
        self.canvas.refresh()

    # --------------------------------------------------------------------------

    def populate_categories(self):
        items = self.keypad_manager.get_checked_category_items()
        attr_box = self.digital_sketch_widget.categoryAttrVerticalLayout
        delete_keypad_items(attr_box)

        if len(items) > 2:
            chunks = split_array_to_chunks(items)
            for chunk in chunks:
                attr_box.addWidget(self.populate_buttons_from_list(chunk))
        else:
            attr_box.addWidget(self.populate_buttons_from_list(items))
        attr_box.addStretch()

    # --------------------------------------------------------------------------

    def button_clicked(self, button_name, btn):
        if self.text_changed:
            btn.setChecked(False)
        else:
            btn.setChecked(True)
        self.clicked_buttons.add(btn)
        if self.feature_string == "":
            self.feature_string = button_name

        # elif button_name not in self.feature_string:
        #     self.feature_string = f'{self.feature_string}{button_name}'
        else:
            self.feature_string = f'{self.feature_string}{button_name}'

        self.update_code_line_edit()

    # --------------------------------------------------------------------------

    def setup_digitizing(self, layer, layer_type):
        """Setup digitizing mode with automated attribute handling"""
        # Make layer active and editable
        if layer is None:
            self.iface.messageBar().pushMessage("Error", f"There is no {layer_type} layer created/added. Use the Settings button to assign existing layers to be used by the sketch tool or to create a new project.",
                                                level=Qgis.Critical, duration=5)
            self.check_for_current_selection()
            return
        self.feature_identify_tool.remove_highlight()
        self.check_for_current_selection(layer_type)
        self.iface.setActiveLayer(layer)
        if self.digitizing_tool is not None:
            self.iface.mapCanvas().unsetMapTool(self.digitizing_tool)

        if layer_type == 'lines':
            self.setup_stream_digitizing(layer, self.multiline_tool)

        elif layer_type == 'points':
            self.setup_stream_digitizing(layer, self.point_tool)

        elif layer_type == 'polygons':
            self.setup_stream_digitizing(layer, self.polygon_tool)

        # Connect to feature added signal
        layer.featureAdded.connect(lambda fid: self.process_layer_after_adding(fid, layer, layer_type))

    # --------------------------------------------------------------------------

    def zoom_to_map(self, is_zoom_in):
        self.zoom_tool.zoom_map(is_zoom_in)

    # --------------------------------------------------------------------------

    def save_and_pan(self):
        self.save_layers()
        self.remove_digitizing_tool()
        self.digital_sketch_widget.saveAndPanPushButton.setChecked(True)
        self.check_for_current_selection('save-and-pan')

    # --------------------------------------------------------------------------

    def save_layers(self):
        self.change_gps_settings(False)
        self.check_for_current_selection()

        QgsApplication.messageLog().logMessage("Save layers is called", 'DigitalSketchPlugin')
        if self.point_layer.isEditable():
            QgsApplication.messageLog().logMessage("Point layer is editable", 'DigitalSketchPlugin')
            self.point_layer.commitChanges()  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to point layer!",
                                                level=Qgis.Success)

        if self.line_layer.isEditable():
            QgsApplication.messageLog().logMessage("Line layer is editable", 'DigitalSketchPlugin')
            self.line_layer.commitChanges()  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to line layer!",
                                                level=Qgis.Success)

        if self.polygon_layer.isEditable():
            QgsApplication.messageLog().logMessage("Polygon layer is editable", 'DigitalSketchPlugin')
            self.polygon_layer.commitChanges()  # Save the changes
            self.iface.messageBar().pushMessage("Success", "Changes committed successfully to polygon layer!",
                                                level=Qgis.Success)

    # --------------------------------------------------------------------------

    def layer_removed(self, layer_id):
        if 'sketch_' in layer_id:
            attr_box = self.digital_sketch_widget.categoryAttrVerticalLayout
            delete_keypad_items(attr_box)
            self.show_error_message('Sketch layer removed')

            if 'sketch_lines' in layer_id:
                self.line_layer = None
            elif 'sketch_polygons' in layer_id:
                self.polygon_layer = None
            elif 'sketch_points' in layer_id:
                self.point_layer = None
    # --------------------------------------------------------------------------

    def show_error_message(self, message):
        msg = self.iface.messageBar().createMessage(f"Error: {message}")
        btn = QPushButton("Please define your sketch layers or create new ones")
        btn.clicked.connect(lambda: self.redefine_layers(msg))
        btn.setMinimumHeight(30)
        font = btn.font()
        font.setPointSize(11)
        btn.setFont(font)

        msg.layout().addWidget(btn)
        self.iface.messageBar().pushWidget(msg, level=Qgis.Critical, duration=0)

    # --------------------------------------------------------------------------

    def redefine_layers(self, message):
        message.dismiss()
        if self.attributes is not None:
            self.attributes["use_existing"] = False
        self.open_settings()

    # --------------------------------------------------------------------------

    def change_gps_settings(self, start_digitizing):
        gps = self.iface.mainWindow().findChild(QWidget, 'QgsGpsInformationWidgetBase')
        popup_btn = gps.findChild(QToolButton, "mBtnPopupOptions")

        if popup_btn:
            btn_menu = popup_btn.menu()
            # for act in btn_menu.actions():
            #     default_w = act.defaultWidget()
            #     QgsApplication.messageLog().logMessage(f"type:{default_w.__class__.__name__} {default_w.accessibleName()}",
            #                                                                            'DigitalSketchPlugin')

            for child in btn_menu.findChildren(QWidget):
                if isinstance(child, QRadioButton):
                    if start_digitizing and child.text() == 'Never Recenter':
                        child.click()
                    elif not start_digitizing and child.text() == 'Recenter Map When Leaving Extent':
                        child.click()
                    # QgsApplication.messageLog().logMessage(f" {child.text()} {start_digitizing}", 'DigitalSketchPlugin')

    # --------------------------------------------------------------------------

    def open_settings(self):
        QgsApplication.messageLog().logMessage("Open settings is called", 'DigitalSketchPlugin')

        settings_dialog = AppSettingsDialog(self.keypad_manager, self.attributes)
        if settings_dialog.exec_() == QDialog.Accepted:
            self.attributes = settings_dialog.get_attributes()
            self.selected_colour = self.attributes['feature_colour']

            if self.attributes['new_project']:
                self.remove_layers()
                self.set_folder_location()
            elif not self.folder_location_set and self.attributes['folder_path'] is not None:
                self.folder_location_set = True
                self.set_folder_location()
            elif self.use_existing != self.attributes['use_existing']:
                self.set_layer_from_existing(self.attributes['layers'])

            if self.point_layer is not None and self.line_layer is not None and self.polygon_layer is not None:
                self.populate_categories()

            else:
                self.show_error_message('All sketch layers are not defined')

            bing_layer = get_bing_layer(self.bing_layer_name)
            if self.attributes['add_bing_imagery'] and not bool(bing_layer):
                self.load_bing_maps()

    # --------------------------------------------------------------------------

    def done_digitizing(self):
        if self.pressed_btn is None:
            self.iface.messageBar().pushMessage("Error", "There is no feature(s) created to be added",
                                                level=Qgis.Critical, duration=5)
            return

        QgsApplication.messageLog().logMessage("Done Digitizing is called", 'DigitalSketchPlugin')
        self.clear_current_btn_selection()
        self.clicked_buttons.clear()
        self.text_changed = False
        code_attr = self.feature_string if not self.text_changed else self.get_code_txt()
        attributes = dict(colour=self.selected_colour, code=code_attr, surveyor=self.attributes['surveyor'],
                          type_txt=self.attributes['type_txt'])
        self.digitizing_tool.save_feature(attributes)

    # --------------------------------------------------------------------------

    def code_text_changed(self):
        self.text_changed = True
        self.clear_current_btn_selection()

    # --------------------------------------------------------------------------

    def clear_current_btn_selection(self):
        if len(self.clicked_buttons) >= 1:
            for btn in self.clicked_buttons:
                btn.setChecked(False)
            self.clicked_buttons.clear()

    # --------------------------------------------------------------------------

    def code_text_changed_finished(self):
        QgsApplication.messageLog().logMessage("text changed finished", 'DigitalSketchPlugin')
        self.feature_string = self.get_code_txt()

    # --------------------------------------------------------------------------

    def remove_feature(self):
        if self.digitizing_tool is not None:
            QgsApplication.messageLog().logMessage("still digitizing", 'DigitalSketchPlugin')
            self.digitizing_tool.remove_feature()

        else:
            if self.selected_attribute is not None:
                QgsApplication.messageLog().logMessage(f"{self.selected_attribute}", 'DigitalSketchPlugin')
                layer_type = self.selected_attribute["type"]
                layer_fid = self.selected_attribute["fid"]
                layer_code = self.selected_attribute["code"]
                if show_delete_confirmation(f'selected feature?\n(Layer: {layer_type} Code: {layer_code})') == QDialog.Accepted:
                    if {"type": layer_type, "fid": layer_fid, "code": layer_code} in self.created_layers_stack:
                        self.created_layers_stack.remove({"type": layer_type, "fid": layer_fid, "code": layer_code})
                else:
                    self.selected_attribute = None
                    self.feature_identify_tool.remove_highlight()
                    return

            else:
                if len(self.created_layers_stack) == 0:
                    return

                QgsApplication.messageLog().logMessage(f"{self.created_layers_stack}", 'DigitalSketchPlugin')
                last_index = len(self.created_layers_stack)-1
                last_layer = self.created_layers_stack[last_index]
                layer_type = last_layer["type"]
                layer_fid = last_layer["fid"]
                layer_code = last_layer["code"]
                if show_delete_confirmation(f'most recent feature?\n(Layer: {layer_type} Code: {layer_code})') == QDialog.Accepted:
                    self.created_layers_stack.pop()
                    QgsApplication.messageLog().logMessage(f"{self.created_layers_stack}", 'DigitalSketchPlugin')
                else:
                    return

            if "lines" in layer_type:
                self.delete_feature(self.line_layer, layer_fid)

            elif "points" in layer_type:
                self.delete_feature(self.point_layer, layer_fid)

            elif "polygons" in layer_type:
                self.delete_feature(self.polygon_layer, layer_fid)

    # --------------------------------------------------------------------------

    def delete_feature(self, layer, fid):
        self.feature_identify_tool.remove_highlight()
        layer.startEditing()
        layer.deleteFeature(fid)
        layer.commitChanges()
        self.selected_attribute = None

    # --------------------------------------------------------------------------

    def setup_stream_digitizing(self, layer, tool):
        """Setup digitizing mode using stylus events"""
        self.change_gps_settings(True)
        self.iface.mapCanvas().refresh()
        self.iface.setActiveLayer(layer)
        layer.startEditing()
        self.digitizing_tool = tool
        self.iface.mapCanvas().setMapTool(self.digitizing_tool)

    # --------------------------------------------------------------------------

    def remove_digitizing_tool(self):
        self.reset_selection_digitize_tool()
        self.iface.actionPan().trigger()

    # --------------------------------------------------------------------------

    def setup_feature_identify_tool(self):
        self.save_layers()
        self.check_for_current_selection('select')
        self.digital_sketch_widget.selectPushButton.setChecked(True)
        self.reset_selection_digitize_tool()
        self.iface.mapCanvas().setMapTool(self.feature_identify_tool)

    # --------------------------------------------------------------------------

    def reset_selection_digitize_tool(self):
        self.selected_attribute = None
        self.highlight = None
        self.vertex_marker = None
        if self.digitizing_tool is not None:
            self.iface.mapCanvas().unsetMapTool(self.digitizing_tool)
            self.digitizing_tool = None

    # --------------------------------------------------------------------------

    def process_layer_after_adding(self, fid, layer, layer_type):
        """Automatically populate attributes for new features"""
        feature = layer.getFeature(fid)
        code = feature.attribute("Code")
        self.layers_saved += 1
        already_exist = {"type": layer_type, "fid": fid, "code": code} in self.created_layers_stack
        if fid > 0 and not already_exist:
            self.created_layers_stack.append({"type": layer.name(), "fid": fid, "code": code})

        if layer_type == 'polygons':
            apply_symbology(layer, self.iface)

        if self.layers_saved == self.digitizing_tool.number_of_items_to_update:
            self.layers_saved = 0
            self.feature_string = ""
            self.update_code_line_edit()

    # --------------------------------------------------------------------------

    def create_geopackage_file(self, project_name):
        QgsApplication.messageLog().logMessage('creating new gpkg file', 'DigitalSketchPlugin')
        date_time_str = datetime.now().strftime("%d-%m-%Y_%I-%M-%p")
        gpkg_file_name = f"{project_name}_{date_time_str}.gpkg"
        gpkg_file_name = os.path.join(self.folder_location, gpkg_file_name)
        QgsApplication.messageLog().logMessage(f'file name: {gpkg_file_name} file path: {gpkg_file_name}',
                                               'DigitalSketchPlugin')

        self.project_crs = str(self.canvas.mapSettings().destinationCrs().toProj())
        if self.project_crs is None:
            self.project_crs = '+proj=longlat +datum=WGS84 +no_defs'

        create_geopackage_file(gpkg_file_name, self.project_crs)

        self.point_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=sketch-points", f"{project_name}-sketch-points", "ogr")
        self.line_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=sketch-lines", f"{project_name}-sketch-lines", "ogr")
        self.polygon_layer = QgsVectorLayer(f"{gpkg_file_name}|layername=sketch-polygons", f"{project_name}-sketch-polygons", "ogr")

        QgsProject.instance().addMapLayer(self.polygon_layer)
        QgsProject.instance().addMapLayer(self.line_layer)
        QgsProject.instance().addMapLayer(self.point_layer)

        self.set_style_and_digitizing_tool()

    #--------------------------------------------------------------------------

    def  check_for_current_selection(self, selection=None):
        if self.pressed_btn is not None:
            QgsApplication.messageLog().logMessage(f"btn already pressed {self.pressed_btn}", 'DigitalSketchPlugin')
            # self.save_layers()

            if self.pressed_btn == 'lines':
                self.digital_sketch_widget.linePushButton.setChecked(False)
            elif self.pressed_btn == 'points':
                self.digital_sketch_widget.pointPushButton.setChecked(False)
            elif self.pressed_btn == 'polygons':
                self.digital_sketch_widget.polygonPushButton.setChecked(False)
            elif self.pressed_btn == 'save-and-pan':
                self.digital_sketch_widget.saveAndPanPushButton.setChecked(False)
            elif self.pressed_btn == 'select':
                self.digital_sketch_widget.selectPushButton.setChecked(False)

        if selection is not  None:
            self.pressed_btn = selection

        elif selection is None:
            self.pressed_btn = None
            self.digital_sketch_widget.linePushButton.setChecked(False)
            self.digital_sketch_widget.pointPushButton.setChecked(False)
            self.digital_sketch_widget.polygonPushButton.setChecked(False)
            self.digital_sketch_widget.saveAndPanPushButton.setChecked(False)
            self.digital_sketch_widget.selectPushButton.setChecked(False)

    # --------------------------------------------------------------------------

    def populate_buttons_from_list(self, items):
        margin = QMargins(1,1,1,1)
        layout = QHBoxLayout()
        layout.setContentsMargins(margin)
        height = self.attributes["height"]
        widget = QWidget()
        widget.setMinimumHeight(height + 1)
        widget.setMaximumHeight(height + 1)

        for i in items:
            light_colour = adjust_color(i["colour"], 30)
            btn = QPushButton(i["item"])
            btn.setMinimumHeight(height)
            btn.setMaximumHeight(height)
            btn.setMinimumWidth(self.attributes["width"])
            btn.setMaximumWidth(self.attributes["width"])
            btn.setFont(self.attributes["font"])
            btn.setCheckable(True)
            btn.setStyleSheet(f"""
                            QPushButton {{
                                background-color: {i["colour"]};
                                color: {self.attributes["colour"]};
                                border-radius: 5px;
                                padding: 2px 2px;
                            }}
                            QPushButton:hover {{
                                background-color: {light_colour};
                            }}
                            QPushButton:checked {{
                                border: 2px solid black
                            }}
                            """)
            layout.addWidget(btn)
            btn.clicked.connect(lambda checked, btn_name=i["item"], clicked_btn=btn: self.button_clicked(btn_name, clicked_btn))
            layout.setContentsMargins(1, 1, 1, 1)
            layout.setSpacing(2)

        layout.addItem(QSpacerItem(40, 30, QSizePolicy.Expanding, QSizePolicy.Minimum))
        layout.insertStretch(-1, 100)
        widget.setLayout(layout)
        return widget

    # --------------------------------------------------------------------------

    def update_code_line_edit(self):
        self.digital_sketch_widget.codeLineEdit.setText(self.feature_string)

    # --------------------------------------------------------------------------

    def get_code_txt(self):
        return self.digital_sketch_widget.codeLineEdit.text().strip()

    # --------------------------------------------------------------------------

    def set_style_and_digitizing_tool(self):
        if self.point_layer is not None:
            self.point_layer.loadNamedStyle(self.point_style)
            self.point_tool = StreamDigitizingTool(self.iface, self.point_layer, 'points')

        if self.polygon_layer is not None:
            self.polygon_layer.loadNamedStyle(self.polygon_style)
            self.polygon_tool = StreamDigitizingTool(self.iface, self.polygon_layer, 'polygons')

        if self.line_layer is not None:
            self.line_layer.loadNamedStyle(self.line_style)
            self.multiline_tool = MultiLineDigitizingTool(self.iface, self.line_layer)

        self.canvas.refresh()

    # --------------------------------------------------------------------------

    def update_selected_layer_style(self):
        layer_type = self.selected_attribute["type"]
        layer_fid = self.selected_attribute["fid"]

        layer = None
        if "lines" in layer_type:
            layer = self.line_layer
        elif "points" in layer_type:
            layer = self.point_layer

        elif "polygons" in layer_type:
            layer = self.polygon_layer

        layer.startEditing()
        QgsApplication.messageLog().logMessage(f"layer.fields() {layer.fields()}", 'DigitalSketchPlugin')

        # layer.dataProvider().changeAttributeValues({
        #     layer_fid: {layer.fields().lookupField('style'): 'highlight'}
        # })

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING DigitalSketchMappingTool"

        # disconnects
        self.digital_sketch_widget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD DigitalSketchMappingTool"

        # for action in self.actions:
        #     self.iface.removePluginMenu(
        #         self.tr(u'&Digital Sketch Mapping Tool'),
        #         action)
        #     self.iface.removeToolBarIcon(action)
        # # remove the toolbar
        # del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING DigitalSketchMappingTool"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)

            # connect to provide cleanup on closing of dockwidget
            self.digital_sketch_widget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.digital_sketch_widget)
            self.digital_sketch_widget.show()
